version: "3.7"

services:

  proxy:
    image: nginx:1.13-alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/app/
      - ./docker/nginx:/etc/nginx/conf.d/

  app:
    build:
      context: .
    #    image: google_app
    container_name: app
    restart: unless-stopped

#  database:
#    image: mysql:5.7
#    container_name: database
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_USER: ${DB_USERNAME}
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
